/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package checkerboard;

import javafx.scene.layout.AnchorPane;
import javafx.scene.paint.Color;

/**
 *
 * @author jonahzukosky
 */
public class CheckerboardClass {
    private int numRows;
    private int numColumns;
    
    private double boardWidth;
    private double boardHeight;
    
    private static final Color DEFAULT_DARK = Color.BLACK;
    private static final Color DEFAULT_LIGHT = Color.RED;
    
    private Color darkColor;
    private Color lightColor;

    
    CheckerboardClass(int numRows,int numColumns,double boardWidth, double boardHeight){
        this(numRows,numColumns,boardWidth,boardHeight,DEFAULT_DARK,DEFAULT_LIGHT);
    }
    
    CheckerboardClass(int numRows,int numColumns,double boardWidth,double boardHeight,Color darkColor,Color lightColor){
        
        
        this.numRows = numRows;
        this.numColumns = numColumns;
        this.boardWidth = boardWidth;
        this.boardHeight = boardHeight;
        this.darkColor = darkColor;
        this.lightColor = lightColor;
        
        
    }
    
    public AnchorPane build(){
        //Builds the board UI and returns an AnchorPane
        AnchorPane anchorPane = new AnchorPane();
        
        
        return anchorPane;
    }
    
    public AnchorPane getBoard(){
       //returns the AnchorPane generated by build() or null if one hasn’t been built yet.
       AnchorPane anchorPane = build();
       
       
       return anchorPane;
    }
    
    public int getNumRows() {
        return numRows;
    }

    public int getNumColumns() {
        return numColumns;
    }

    public double getBoardWidth() {
        return boardWidth;
    }

    public double getBoardHeight() {
        return boardHeight;
    }

    public Color getDarkColor() {
        return darkColor;
    }

    public Color getLightColor() {
        return lightColor;
    }
    
    
}
